/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.android.unscramble.ui.game


const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

// List with all the words for the Game
val allWordsList: List<String> =
    listOf("animal",
        "auto",
        "anecdota",
        "alfabeto",
        "todos",
        "impresionante",
        "levantarse",
        "globo",
        "siete",
        "banco",
        "mejor",
        "cumpleanos",
        "libro ",
        "maletin",
        "camara",
        "camping",
        "vela",
        "gato",
        "coliflor",
        "charla",
        "ninos",
        "clase",
        "clasico",
        "aula",
        "cafe",
        "colorido",
        "galleta",
        "creativo",
        "crucero",
        "baile",
        "diurno",
        "dinosaurio",
        "puerta",
        "cena",
        "sueno",
        "anochecer",
        "comer",
        "elefante ",
        "esmeralda",
        "sustos",
        "electrico",
        "acabado",
        "flores",
        "seguir",
        "zorro",
        "marco",
        "libre",
        "frecuente",
        "embudo",
        "verde",
        "guitarra",
        "comestibles",
        "vaso",
        "genial",
        "risita",
        "peluqueria",
        "mitad",
        "casero",
        "sucede",
        "miel",
        "prisa",
        "cien",
        "hielo ",
        "iglu",
        "invertir",
        "invitar",
        "icono",
        "presentar",
        "bromas",
        "joyas",
        "diario",
        "saltar",
        "unirse",
        "canguro",
        "teclado",
        "cocina",
        "koala",
        "amable",
        "telescopio",
        "paisaje",
        "tarde",
        "risa",
        "aprendizaje",
        "limon",
        "letra",
        "lirio",
        "revista",
        "marino ",
        "malvavisco",
        "laberinto",
        "meditar",
        "melodía",
        "minuto",
        "monumento",
        "luna",
        "moto",
        "montana",
        "musica",
        "norte",
        "nariz",
        "noche",
        "nombre",
        "nunca",
        "negociar",
        "numero",
        "opuesto",
        "pulpo",
        "roble",
        "orden",
        "abrir",
        "polar",
        "empacar",
        "pintar ",
        "persona",
        "picnic",
        "almohada",
        "pizza",
        "caramelo",
        "presentacion",
        "cachorro",
        "rompecabezas",
        "receta",
        "lanzamiento",
        "restaurante",
        "girar",
        "motor",
        "habitacion",
        "correr",
        "secreto",
        "semilla",
        "barco",
        "camisa",
        "deberia",
        "pequeña",
        "colombia",
        "estrellas",
        "habilidad ",
        "calle",
        "estilo",
        "amanecer",
        "taxi",
        "ordenado",
        "cronometro",
        "juntos",
        "diente",
        "turista",
        "viaje",
        "camion",
        "debajo",
        "util",
        "unicornio",
        "unico",
        "elevacion",
        "uniforme",
        "jarron",
        "violin",
        "visitante",
        "vision",
        "volumen",
        "vista",
        "morsa",
        "vagar",
        "mundo",
        "invierno",
        "bien",
        "torbellino",
        "rayos X",
        "xilofono",
        "yoga",
        "yogur",
        "yoyo",
        "tu",
        "año",
        "delicioso ",
        "cebra",
        "cruzar",
        "zoologia",
        "zona",
        "caminar")